### ISSUE TITLE
Binding style is treated as script style

### ISSUE THREAD

**Issue by pynnl** [sveltejs/eslint-plugin-svelte3#21]
### Environment
- vscode 1.35.1
- node 12.1.0
- svelte@3.6.1
- eslint@6.0.1
- eslint-plugin-svelte3@2.0.0

### Reproduce
![image](https://user-images.githubusercontent.com/31667324/60132557-b83ee280-9769-11e9-98e9-69f9bd271322.png)

### Errors
![image](https://user-images.githubusercontent.com/31667324/60132593-d0166680-9769-11e9-9aec-bd30c1f85028.png)

### Config
```yml
parserOptions:
  ecmaVersion: 2019
  sourceType: module
env:
  es6: true,
  browser: true
plugins:
  - svelte3
overrides:
  - files: '*.svelte'
    processor: svelte3/svelte3
    rules:
      import/first: off
      import/no-duplicates: off
      import/no-mutable-exports: off
      # bugs
      eol-last: off
      no-unused-expressions: off
```

### [repo](https://github.com/pynnl/eslint-plugin-svelte3-21)
